### ISSUE TITLE
Versions below 5.81 are deprecated

### ISSUE THREAD

**Issue by authorIsRight** [Sehat1137/remove-all-vk-comments#1]
Спасибо за скрипт, 

пытался запустить, но столкнулся с такой ошибкой:

{'error_code': 8, 'error_msg': 'Invalid request: versions below 5.81 are deprecated. Version param should be passed as "v". "version" param is invalid and not supported. For more information go to https://vk.com/dev/constant_version_updates', 'request_params': [{'key': 'method', 'value': 'wall.deleteComment'}, {'key': 'oauth', 'value': '1'}, {'key': 'owner_id', 'value': 'скрыл значение'}, {'key': 'item_id', 'value': 'скрыл значение'}, {'key': 'v', 'value': '5.74'}]}, 'https://api.vk.com/method/wall.deleteComment')

надеюсь у тебя получится, а то я уже и не помню, что писал лет 5 назад, сам понимаешь в какие времена живем

**Comment by Sehat1137** [comment]
Привет, у меня к сожалению сейчас нет выгруженных комментариев под рукой. Ошибка в том, что поддерживаемая версия vk_api изменилась, её нужно руками установить как более высокую.

На 47 строке это можно сделать:

`
await self.api.wall.deleteComment(owner_id=owner_id, comment_id=comment_id, v="5.131")
`

Этих изменений должно быть достаточно, т.к. никакие из используемых мной методов не измнелись в последующих версиях VK API. 

Я пока запрошу архив, чтобы руками проверить, что это работает и чуть позже выпущу патч.

**Comment by Sehat1137** [comment]
https://github.com/Sehat1137/remove-all-vk-comments

**Comment by Sehat1137** [comment]
https://github.com/Sehat1137/remove-all-vk-comments/commit/7c99c334aa12cf6d5fd4fc09f554acc69d29c4de
