### ISSUE TITLE
 asyncio.run(processor.run()) AttributeError: module 'asyncio' has no attribute 'run'

### ISSUE THREAD

**Issue by Nau077** [Sehat1137/remove-all-vk-comments#2]
Got error after running:

Traceback (most recent call last):
  File "delete_all_comments.py", line 91, in <module>
    asyncio.run(processor.run())
AttributeError: module 'asyncio' has no attribute 'run'

os: linux ubuntu 18

requirements instaleed with success

pip 3 is also installed

**Comment by Sehat1137** [comment]
Sorry, it`s my bad, didn't put it in the readme, but for correct work you need use python3.7.X or later version

Default python interpreter in Ubuntu 18.04 it's python3.6.X. You may install python3.7.X or later also you need install pip for your python version and install requirements again for new interpreter

Install python
`sudo apt update -y`
`sudo apt install python3.9 -y`

Install pip
Download the script, from https://bootstrap.pypa.io/get-pip.py
`python3.9 get-pip.py`

Install requirements 
`pip3.9 install -r requirements.txt`

After this you can try run script again:
`python3.9 delete_all_comments.py`
